package com.kraptor

import com.lagradost.cloudstream3.plugins.CloudstreamPlugin
import com.lagradost.cloudstream3.extractors.EmturbovidExtractor
import com.lagradost.cloudstream3.extractors.StreamTape
import com.lagradost.cloudstream3.extractors.VidStack
import com.lagradost.cloudstream3.extractors.Voe
import com.lagradost.cloudstream3.plugins.BasePlugin

@CloudstreamPlugin
class JavEnSpanishPlugin : BasePlugin() {
    override fun load() {
        registerMainAPI(JavEnSpanish())

        // Core extractors used by the site
        registerExtractorAPI(StreamTape())
        registerExtractorAPI(StreamTapeNet())
        registerExtractorAPI(StreamTapeXyz())
        registerExtractorAPI(Turboplayers())
        registerExtractorAPI(DoodStream())
        registerExtractorAPI(DoodDoply())
        registerExtractorAPI(DoodVideo())
        registerExtractorAPI(Ds2Play())
        registerExtractorAPI(d000d())
        registerExtractorAPI(Dooood())
        registerExtractorAPI(DoodPmExtractor())
        registerExtractorAPI(Playmogo())

        // VidHide / Filelions family
        registerExtractorAPI(VidHidePro())
        registerExtractorAPI(VidHidePro1())
        registerExtractorAPI(VidHidePro2())
        registerExtractorAPI(VidHidePro3())
        registerExtractorAPI(VidHidePro4())
        registerExtractorAPI(VidHidePro6())
        registerExtractorAPI(VidHidePro7())
        registerExtractorAPI(VidhideVIP())
        registerExtractorAPI(Javlion())
        registerExtractorAPI(Dhcplay())
        registerExtractorAPI(Smoothpre())
        registerExtractorAPI(Dhtpre())
        registerExtractorAPI(Peytonepre())
        registerExtractorAPI(Movearnpre())
        registerExtractorAPI(Dintezuvio())
        registerExtractorAPI(HgLink())
        registerExtractorAPI(RyderJet())
        registerExtractorAPI(MyCloudZ())

        // Streamwish family
        registerExtractorAPI(Streamwish())
        registerExtractorAPI(Streamhihi())
        registerExtractorAPI(Javsw())
        registerExtractorAPI(swhoi())

        // Filemoon / Byse (critical for FM button)
        registerExtractorAPI(Filemoon())
        registerExtractorAPI(KPFilemoonSx())
        registerExtractorAPI(KPFilemoonIn())
        registerExtractorAPI(KPFilemoonLink())
        registerExtractorAPI(KPFilemoonWf())
        registerExtractorAPI(KPFilemoonEu())
        registerExtractorAPI(KPFilemoonArt())
        registerExtractorAPI(KPFilemoonNl())
        registerExtractorAPI(KPCinegrab())
        registerExtractorAPI(KPMoonmov())
        registerExtractorAPI(KPNineSixAr())
        registerExtractorAPI(KPKerapoxy())
        registerExtractorAPI(KPFurher())
        registerExtractorAPI(KPOneAzayf9w())
        registerExtractorAPI(KPEightOneU6xl9d())
        registerExtractorAPI(KPSmdfs40r())
        registerExtractorAPI(KPC1z39())
        registerExtractorAPI(KPBf0skv())
        registerExtractorAPI(KPZ1ekv717())
        registerExtractorAPI(KPL1afav())
        registerExtractorAPI(KPTwoTwoTwoi8x())
        registerExtractorAPI(KPEightMhlloqo())
        registerExtractorAPI(KPF51rm())
        registerExtractorAPI(KPXcoic())
        registerExtractorAPI(KPBoosteradx())
        registerExtractorAPI(KPStreamlyplayer())
        registerExtractorAPI(KPStreamlyplayero())
        registerExtractorAPI(KPBysewihe())
        registerExtractorAPI(KPByselapuix())
        registerExtractorAPI(KPEmbedplaybyse())
        registerExtractorAPI(KPSb1254w9megshle())
        registerExtractorAPI(KPMoflixStream())
        registerExtractorAPI(KPBysezoxexe())
        registerExtractorAPI(KPF16px())
        registerExtractorAPI(KPBysesayeveum())
        registerExtractorAPI(KPBysetayico())
        registerExtractorAPI(KPBysevepoin())
        registerExtractorAPI(KPBysezejataos())
        registerExtractorAPI(KPBysekoze())
        registerExtractorAPI(KPBysesukior())
        registerExtractorAPI(KPBysejikuar())
        registerExtractorAPI(KPBysefujedu())
        registerExtractorAPI(KPBysedikamoum())
        registerExtractorAPI(KPBysebuho())
        registerExtractorAPI(KPByseSx())
        registerExtractorAPI(KPByseqekaho())
        registerExtractorAPI(Javmoon())

        // Other useful ones
        registerExtractorAPI(CloudWish())
        registerExtractorAPI(VidNest())
        registerExtractorAPI(MixDropis())
        registerExtractorAPI(MixDropAG())
        registerExtractorAPI(MixDropMy())
        registerExtractorAPI(Javggvideo())
        registerExtractorAPI(EmturbovidExtractor())
        registerExtractorAPI(VidStack())
        registerExtractorAPI(StbP2P())
        registerExtractorAPI(Playerupnone())
        registerExtractorAPI(Turtleviplay())
        registerExtractorAPI(Turboviplay())
        registerExtractorAPI(Vidguardto())
        registerExtractorAPI(Player4Me())
        registerExtractorAPI(Vip4me())
        registerExtractorAPI(RPMShare())
        registerExtractorAPI(UpnsOnline())
        registerExtractorAPI(EmbedSeek())
        registerExtractorAPI(VipSeekPlayer())
        registerExtractorAPI(EasyVidPlayer())
        registerExtractorAPI(VipEasyVidPlayer())
        registerExtractorAPI(Voe())
        registerExtractorAPI(Stape())
        registerExtractorAPI(StreamTAPE())
        registerExtractorAPI(ShaveTape())
        registerExtractorAPI(Watchadsontape())
        registerExtractorAPI(Lancewhoisdifficult())
        registerExtractorAPI(Javlesbians())
        registerExtractorAPI(Stevenfamilyedge())
        registerExtractorAPI(LULUSTREAM())
        registerExtractorAPI(LULUVDO())
        registerExtractorAPI(LULUVDOO())
        registerExtractorAPI(LULUPVP())
        registerExtractorAPI(LULUDLC())
        registerExtractorAPI(LULU0())
        registerExtractorAPI(LULUX08())
        registerExtractorAPI(Playmate())
        registerExtractorAPI(Morencius())
    }
}